### ISSUE TITLE
Luisa Gonzalez-portfolio page

### ISSUE THREAD

**Issue by lgmusic24** [ga-dc/wdi15#1]
file:///Users/lgmusic24/lgmusic24.github.io/index.html

**Comment by jsm13** [comment]
You'll want to push your work to your repo here (https://github.com/lgmusic24/lgmusic24.github.io) and then open an issue on https://github.com/ga-wdi-exercises/portfolio_pages/issues with a link to the github page (https://lgmusic24.github.io/)
